tvg/agcs/urls.py
from django.conf.urls import url
from . import views

app_name = "agcs"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^form/$', views.form, name="form"),
    url(r'^companies/$', views.form,  name="companies_list"),
    url(r'^companies/(?P<pk>\d+)$', views.CompaniesDetailView.as_view(), name="companies_detail"),
    url(r'^logout/', views.logout, name="logout"),

]

tvg/tvg/urls.py
from django.contrib.auth import views
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("agcs.urls")),
    url(r'accounts/login/$', views.login, name="login"),
    url(r'accounts/logout/$', views.logout, name="logout", kwargs={"next_page": "/"})

]

tvg/agcs/models.py
from django.db import models

# Create your models here.
#I want the Company as the parent class and the yearly data as child classes
class Companies(models.Model):
    name = models.CharField(max_length=100)
    DSCD = models.CharField(max_length=15)
    nation = models.CharField(max_length=100)
    ESG = models.CharField(max_length=15)
    ENV = models.CharField(max_length=15)
    SOC = models.CharField(max_length=15)
    CGV = models.CharField(max_length=15)
    QUAL = models.CharField(max_length=15)

    def __str__(self):
        return self.name + " - " + self.DSCD + " - " + str(self.ESG)

class Years(models.Model):
    company = models.ForeignKey(Companies, on_delete=models.CASCADE)
    year = models.CharField(max_length=4)
    ESG = models.CharField(max_length=15)
    ENV = models.CharField(max_length=15)
    SOC = models.CharField(max_length=15)
    CGV = models.CharField(max_length=15)
    QUAL = models.CharField(max_length=15)


    def __str__(self):
        return str(self.company.name) + " - " + str(self.year)

tvg/agcs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import logout
from .models import Companies, Years

from django.views.generic import ListView, DetailView

# Create your views here.
def index(request):
    if request.user.is_authenticated():
        return render(request, "index.html")
    else:
        return redirect("login")

def form(request):
    list_obj = []
    # for company in Companies.objects.filter(name__contains="all"):
    #     list_obj.append(company)

    for company in Companies.objects.all():
        list_obj.append(company)

    context = {"context": list_obj}
    return render(request, "companies_list.html", context)

def logout_view(request):
    logout(request)


class CompaniesListView(ListView):
    model = Companies

class CompaniesDetailView(DetailView):
    model = Companies

tvg/agcs/templates/agcs/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <!-- Chart.js -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.js"></script>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <!-- <link rel="stylesheet" href="{% static "css/blog.css" %}"> -->

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One|Playfair+Display" rel="stylesheet">

    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-default techfont custom-navbar">
  <div class="container">
    <ul class="nav navbar-nav">
      <li><a class="navbar-brand bigbrand" style="color: rgb(121,23,49); font-weight: bold; font-family: 'Playfair Display', serif; font-size: 35px;">The Value Group</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <li>
          <a href="{% url 'agcs:companies_list' %}">Companies</a>
        </li>
        <li>
          <a href="{% url 'logout' %}">Log Out</a>
        </li>
        <li>
          <a>Welcome, {{user.username}}</a>
        </li>
        {% else %}
        <li><a class"nav navbar-right" href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span></a></li>
      {% endif %}
    </ul>
  </div>
</nav>

<div class="content container">
  <div class="row">
    <div class="col-md-8">
      <div class="blog_posts">
        {% block content %}
        {% endblock %}

      </div>
    </div>
  </div>
</div>


  </body>
</html>

tvg/agcs/templates/agcs/companies_detail.html
{% extends "base.html" %}
{% block title %}{{companies.name}}{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<div class="col-md-6">

  <ul style="list-style: none; padding-top: 20px">
    <li><p><strong>Name:</strong> {{companies.name}}</p></li>
    <li><p><strong>DS-Code:</strong> {{companies.DSCD}}</p></li>
    <li><p><strong>ESG-Score:</strong> {{companies.ESG}}</p></li>
    <li><p><strong>Environmental Score:</strong> {{companies.ENV}}</p></li>
    <li><p><strong>Social Score:</strong> {{companies.SOC}}</p></li>
    <li><p><strong>Governance Score:</strong> {{companies.CGV}}</p></li>
    <li><p><strong>Quality Score:</strong> {{companies.QUAL}}</p></li>
    <li><a href="{% url 'agcs:companies_list' %}"><strong>Back</strong></a></li>
  </ul>
</div>

<div class="col-md-6">
  <canvas id="myChart" width="400%" height="400%"></canvas>
  <script>
  var ctx = document.getElementById("myChart").getContext('2d');
  var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
          labels: ["ESG Score", "Environmental Score", "Social Score", "Governance Score", "Quality Score"],
          datasets: [{
              label: 'Score Value',
              data: [{{companies.ESG}}, {{companies.ENV}}, {{companies.SOC}}, {{companies.CGV}}, {{companies.QUAL}}],
              backgroundColor: [
                  'rgba(255, 206, 86, 0.2)',
                  'rgba(75, 192, 192, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(54, 162, 235, 0.2)',
                  'rgba(121, 23, 49, 0.2)'

              ],
              borderColor: [
                  'rgba(255, 206, 86, 1)',
                  'rgba(75, 192, 192, 1)',
                  'rgba(255,99,132,1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(121, 23, 49, 1)'

              ],
              borderWidth: 1
          }]
      },
      options: {
        responsive: false,
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero:true,
                      max:100
                  }
              }]
          }
      }
  });
  </script>
</div>


  <div class="chartjs-wrapper col-md-6" style="width: 110%; padding-left: 60px; margin-top: 15px margin-bottom: 10px">

    <canvas id="chartjs-0" class="chartjs" width="undefined" height="undefined"></canvas>
    <script>
    new Chart(document.getElementById("chartjs-0"),
    {"type":"line",
      "data":{"labels":
        [{% for year in companies.years_set.all %}
            {{year.year}},
        {% endfor %}],
        "datasets":
          [{"label":"ESG Score",
          "data":[{% for year in companies.years_set.all %}
                    {{year.ESG}},
                  {% endfor %}],
          "fill":true,
          "borderColor":"rgb(255, 206, 86)",
          "lineTension":0.1},
          {"label":"Environmental Score",
          "data":[{% for year in companies.years_set.all %}
                    {{year.ENV}},
                  {% endfor %}],
          "fill":false,
          "borderColor":"rgb(75, 192, 192)",
          "lineTension":0.1},
          {"label":"Social Score",
          "data":[{% for year in companies.years_set.all %}
                    {{year.SOC}},
                  {% endfor %}],
          "fill":false,
          "borderColor":"rgb(255,99,132)",
          "lineTension":0.1},
          {"label":"Governance Score",
          "data":[{% for year in companies.years_set.all %}
                    {{year.CGV}},
                  {% endfor %}],
          "fill":false,
          "borderColor":"rgb(54, 162, 235)",
          "lineTension":0.1},
          {"label":"Quality Score",
          "data":[{% for year in companies.years_set.all %}
                    {{year.QUAL}},
                  {% endfor %}],
          "fill":false,
          "borderColor":"rgb(121, 23, 49)",
          "lineTension":0.1}]},"options":{}});
      </script>
    </div>

{% else %}
<p>Please <a href="{% url 'login' %}">log in</a>.</p>

{% endif %}

{% endblock %}

tvg/agcs/templates/agcs/companies_list.html
{% extends "base.html" %}
{% block title %}Select a Company{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="container" style="margin-top: 15%;">

  <div class="col-md-2"></div>
  <div class="form-group col-md-8">

    <form name="Testform" action="">
      <input type="text" class="inputbox form-control" id="answer" style="width: 80%; margin-bottom: 5px;" placeholder="Enter Company Name">
        <div class="btn btn-default" id="clickBox" style="width: 80%">Search</div>
    </form>
  </div>

  <div class="col-md-2"></div>
</div>


    <div class="container" id="suggest"></div>


<script type="text/javascript">
  var allComps = [];
  var compIDs = [];

  //put all companies in list:
  {% for company in context %}
    allComps.push("{{ company.name }}");
    compIDs.push("{{ company.id }}");
  {% endfor %}

  document.getElementById("clickBox").addEventListener("click", function() {
    if (document.getElementById("answer").value.length > 0) {
    search();
  }
  });

  window.addEventListener('keydown',function(e) {
  if(e.keyIdentifier=='U+000A' || e.keyIdentifier=='Enter' || e.keyCode==13) {
    if(e.target.nodeName=='INPUT' && e.target.type=='text') {
      e.preventDefault();
      if (document.getElementById("answer").value.length > 0) {
      search();
    }
      return false;}
    }
  },
  true);



function search() {
  var j = 0;
  document.getElementById("suggest").innerHTML = '<table class="table table-hover"> <thead> <tr> <th>Companies containing <span style="color: red">' + document.getElementById("answer").value + '</span></th></tr></thead><tbody id="tbod"></tbody></table>';
  for (i = 0; i < allComps.length; i++) {
    if (allComps[i].indexOf(document.getElementById("answer").value.toUpperCase()) !== -1) {
      j += 1;
      document.getElementById("tbod").innerHTML += '<tr><th scope=row>' + j + '</th><td><a href="/companies/' + compIDs[i] + '">' +allComps[i] + '</a></td></tr>';
    }
  }
};

</script>

{% endif %}
{% endblock %}

tvg/agcs/templates/agcs/companies_list_alt.html
{% extends "base.html" %}
{% block title %}Select a Company{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<select name="mydropdown" class="styled" onChange="document.location = this.value" value="GO">
{% for company in companies_list %}
  <option value="{% url 'agcs:companies_detail' pk=company.pk %}">{{company.name}}</option>
{% endfor %}
</select>

<br><br>
{% for company in companies_list %}
  <p><a href="{% url 'agcs:companies_detail' pk=company.pk %}">{{company.name}}</a></p>

{% endfor %}

{% else %}
<p>Please <a href="{% url 'login' %}">log in</a>.</p>

{% endif %}
{% endblock %}

tvg/agcs/templates/agcs/index.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}
{% block content %}
<h1>Welcome, {{user.username}}</h1>
{% endblock %}